import 'package:flutter/material.dart';
import 'player_stats_model.dart';

enum AchievementCategory {
  partidas,
  jugadas,
  economia,
}

class AchievementItem {
  final String id;
  final String title;
  final String description;
  final IconData icon;
  final Color iconColor;
  final AchievementCategory category;
  final int targetProgress;
  final int coinReward;
  final int xpReward;
  final int Function(PlayerStatsModel stats) getProgress;

  const AchievementItem({
    required this.id,
    required this.title,
    required this.description,
    required this.icon,
    required this.iconColor,
    required this.category,
    required this.targetProgress,
    required this.coinReward,
    required this.xpReward,
    required this.getProgress,
  });
}

class AchievementCatalog {
  static final List<AchievementItem> allAchievements = [
    // --- LOGROS DESTACADOS INICIALES ---
    AchievementItem(
      id: 'ach_trivilin_1',
      title: 'Maestro del Trivilín',
      description: 'Cantar 1 Trivilín en partida oficial.',
      icon: Icons.auto_awesome_rounded,
      iconColor: const Color(0xFF9333EA),
      category: AchievementCategory.jugadas,
      targetProgress: 1,
      coinReward: 500,
      xpReward: 100,
      getProgress: (s) => s.trivilines,
    ),
    AchievementItem(
      id: 'ach_limpia_10',
      title: 'Rey de la Mesa Limpia',
      description: 'Realizar 10 Mesas Limpias en partidas.',
      icon: Icons.waves_rounded,
      iconColor: const Color(0xFF059669),
      category: AchievementCategory.jugadas,
      targetProgress: 10,
      coinReward: 700,
      xpReward: 140,
      getProgress: (s) => s.mesasLimpias,
    ),
    AchievementItem(
      id: 'ach_caidas_25',
      title: 'Cazador de Caídas',
      description: 'Cantar 25 Caídas a tus rivales.',
      icon: Icons.bolt_rounded,
      iconColor: const Color(0xFFBE123C),
      category: AchievementCategory.jugadas,
      targetProgress: 25,
      coinReward: 600,
      xpReward: 120,
      getProgress: (s) => s.caidasMade,
    ),
    AchievementItem(
      id: 'ach_vip_5',
      title: 'Gallo de Oro',
      description: 'Ganar 5 partidas en Mesas VIP.',
      icon: Icons.military_tech_rounded,
      iconColor: const Color(0xFFEAB308),
      category: AchievementCategory.economia,
      targetProgress: 5,
      coinReward: 1000,
      xpReward: 200,
      getProgress: (s) => s.gamesWon,
    ),
    AchievementItem(
      id: 'ach_teams_3',
      title: 'Invicto en Parejas',
      description: 'Ganar 3 partidas en modo 2 vs 2.',
      icon: Icons.groups_rounded,
      iconColor: const Color(0xFF3B82F6),
      category: AchievementCategory.economia,
      targetProgress: 3,
      coinReward: 400,
      xpReward: 80,
      getProgress: (s) => s.teamWins,
    ),
    AchievementItem(
      id: 'ach_cards_50',
      title: 'Coleccionista de Ases',
      description: 'Acumular 50 cartas ganadas en mesa.',
      icon: Icons.style_rounded,
      iconColor: const Color(0xFF10B981),
      category: AchievementCategory.economia,
      targetProgress: 50,
      coinReward: 300,
      xpReward: 60,
      getProgress: (s) => s.totalCardsWon,
    ),

    // --- CATEGORÍA 1: PARTIDAS Y VICTORIAS (9) ---
    AchievementItem(
      id: 'ach_games_1',
      title: 'Primer Paso',
      description: 'Jugar 1 partida oficial de La Caída.',
      icon: Icons.play_arrow_rounded,
      iconColor: const Color(0xFF38BDF8),
      category: AchievementCategory.partidas,
      targetProgress: 1,
      coinReward: 100,
      xpReward: 20,
      getProgress: (s) => s.gamesPlayed,
    ),
    AchievementItem(
      id: 'ach_games_10',
      title: 'Veterano',
      description: 'Jugar 10 partidas oficiales.',
      icon: Icons.history_edu_rounded,
      iconColor: const Color(0xFF60A5FA),
      category: AchievementCategory.partidas,
      targetProgress: 10,
      coinReward: 300,
      xpReward: 60,
      getProgress: (s) => s.gamesPlayed,
    ),
    AchievementItem(
      id: 'ach_games_50',
      title: 'Curtido',
      description: 'Jugar 50 partidas oficiales.',
      icon: Icons.military_tech_rounded,
      iconColor: const Color(0xFF818CF8),
      category: AchievementCategory.partidas,
      targetProgress: 50,
      coinReward: 800,
      xpReward: 150,
      getProgress: (s) => s.gamesPlayed,
    ),
    AchievementItem(
      id: 'ach_games_100',
      title: 'Leyenda de la Mesa',
      description: 'Jugar 100 partidas oficiales de La Caída.',
      icon: Icons.workspace_premium_rounded,
      iconColor: const Color(0xFFA855F7),
      category: AchievementCategory.partidas,
      targetProgress: 100,
      coinReward: 2000,
      xpReward: 400,
      getProgress: (s) => s.gamesPlayed,
    ),
    AchievementItem(
      id: 'ach_wins_1',
      title: 'Primera Victoria',
      description: 'Ganar tu primera partida.',
      icon: Icons.emoji_events_rounded,
      iconColor: const Color(0xFFFBBF24),
      category: AchievementCategory.partidas,
      targetProgress: 1,
      coinReward: 150,
      xpReward: 30,
      getProgress: (s) => s.gamesWon,
    ),
    AchievementItem(
      id: 'ach_wins_10',
      title: 'Dominador',
      description: 'Ganar 10 partidas oficiales.',
      icon: Icons.military_tech_rounded,
      iconColor: const Color(0xFFF59E0B),
      category: AchievementCategory.partidas,
      targetProgress: 10,
      coinReward: 500,
      xpReward: 100,
      getProgress: (s) => s.gamesWon,
    ),
    AchievementItem(
      id: 'ach_wins_50',
      title: 'Invencible',
      description: 'Ganar 50 partidas oficiales.',
      icon: Icons.auto_awesome_rounded,
      iconColor: const Color(0xFFEAB308),
      category: AchievementCategory.partidas,
      targetProgress: 50,
      coinReward: 1500,
      xpReward: 300,
      getProgress: (s) => s.gamesWon,
    ),
    AchievementItem(
      id: 'ach_streak_3',
      title: 'Racha Imparable',
      description: 'Alcanzar una racha de 3 victorias consecutivas.',
      icon: Icons.local_fire_department_rounded,
      iconColor: const Color(0xFFEA580C),
      category: AchievementCategory.partidas,
      targetProgress: 3,
      coinReward: 400,
      xpReward: 80,
      getProgress: (s) => s.winStreak,
    ),
    AchievementItem(
      id: 'ach_streak_5',
      title: 'En Llamas',
      description: 'Alcanzar una racha de 5 victorias consecutivas.',
      icon: Icons.whatshot_rounded,
      iconColor: const Color(0xFFDC2626),
      category: AchievementCategory.partidas,
      targetProgress: 5,
      coinReward: 1000,
      xpReward: 200,
      getProgress: (s) => s.winStreak,
    ),

    // --- CATEGORÍA 2: JUGADAS Y CANTOS (RESTANTES) ---
    AchievementItem(
      id: 'ach_caida_1',
      title: 'Primer Golpe',
      description: 'Cantar tu primera Caída a un rival.',
      icon: Icons.flash_on_rounded,
      iconColor: const Color(0xFFE11D48),
      category: AchievementCategory.jugadas,
      targetProgress: 1,
      coinReward: 100,
      xpReward: 20,
      getProgress: (s) => s.caidasMade,
    ),
    AchievementItem(
      id: 'ach_caidas_100',
      title: 'Depredador',
      description: 'Cantar 100 Caídas a tus rivales.',
      icon: Icons.dangerous_rounded,
      iconColor: const Color(0xFF881337),
      category: AchievementCategory.jugadas,
      targetProgress: 100,
      coinReward: 2000,
      xpReward: 400,
      getProgress: (s) => s.caidasMade,
    ),
    AchievementItem(
      id: 'ach_limpia_1',
      title: 'Limpieza Perfecta',
      description: 'Realizar 1 Mesa Limpia.',
      icon: Icons.cleaning_services_rounded,
      iconColor: const Color(0xFF0D9488),
      category: AchievementCategory.jugadas,
      targetProgress: 1,
      coinReward: 150,
      xpReward: 30,
      getProgress: (s) => s.mesasLimpias,
    ),
    AchievementItem(
      id: 'ach_rondas_5',
      title: 'Canta que Canta',
      description: 'Cantar 5 Rondas.',
      icon: Icons.music_note_rounded,
      iconColor: const Color(0xFF10B981),
      category: AchievementCategory.jugadas,
      targetProgress: 5,
      coinReward: 250,
      xpReward: 50,
      getProgress: (s) => s.rondas,
    ),
    AchievementItem(
      id: 'ach_patrulla_5',
      title: 'El Guardián',
      description: 'Cantar 5 Patrullas.',
      icon: Icons.shield_moon_rounded,
      iconColor: const Color(0xFF2563EB),
      category: AchievementCategory.jugadas,
      targetProgress: 5,
      coinReward: 300,
      xpReward: 60,
      getProgress: (s) => s.patrullas,
    ),
    AchievementItem(
      id: 'ach_vigia_3',
      title: 'Ojos de Águila',
      description: 'Cantar 3 Vigías.',
      icon: Icons.visibility_rounded,
      iconColor: const Color(0xFF7C3AED),
      category: AchievementCategory.jugadas,
      targetProgress: 3,
      coinReward: 350,
      xpReward: 70,
      getProgress: (s) => s.vigias,
    ),
    AchievementItem(
      id: 'ach_registro_1',
      title: 'Canto de Gala',
      description: 'Cantar 1 Registro en partida oficial.',
      icon: Icons.workspace_premium_rounded,
      iconColor: const Color(0xFFD97706),
      category: AchievementCategory.jugadas,
      targetProgress: 1,
      coinReward: 200,
      xpReward: 40,
      getProgress: (s) => s.registros,
    ),

    // --- CATEGORÍA 3: ECONOMÍA Y RANGO (RESTANTES) ---
    AchievementItem(
      id: 'ach_cards_200',
      title: 'Archivista',
      description: 'Acumular 200 cartas ganadas en mesa.',
      icon: Icons.inventory_2_rounded,
      iconColor: const Color(0xFF047857),
      category: AchievementCategory.economia,
      targetProgress: 200,
      coinReward: 800,
      xpReward: 150,
      getProgress: (s) => s.totalCardsWon,
    ),
    AchievementItem(
      id: 'ach_rank_bronce',
      title: 'Ascenso a Bronce',
      description: 'Alcanzar el rango Bronce (150+ trofeos).',
      icon: Icons.emoji_events_rounded,
      iconColor: const Color(0xFFD97706),
      category: AchievementCategory.economia,
      targetProgress: 150,
      coinReward: 300,
      xpReward: 60,
      getProgress: (s) => s.trophies,
    ),
    AchievementItem(
      id: 'ach_rank_oro',
      title: 'El Dorado',
      description: 'Alcanzar el rango Oro (900+ trofeos).',
      icon: Icons.star_rounded,
      iconColor: const Color(0xFFFDE047),
      category: AchievementCategory.economia,
      targetProgress: 900,
      coinReward: 1000,
      xpReward: 200,
      getProgress: (s) => s.trophies,
    ),
  ];
}
